=== AURA120/first-repository/format.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--<!ELEMENT element-name (#PCDATA)> --> <!--for create a tag, #PCDATA like string data type-->


<!--to create normal tag-->
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT city (#PCDATA)>


<!--to create head tag-->
<!ELEMENT student (id,name,age,city)>


<!--Root tag setting-->
<!ELEMENT students (student*)>


<!--section attribute-->
<!ATTLIST student gender (Male|Female) #REQUIRED> <!--ATTLIST = attribute list-->

<!--type attribute-->
<!ATTLIST age B_day CDATA #REQUIRED>

=== AURA120/first-repository/students.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE students SYSTEM "format.dtd">

<students>

  <student gender ="Male">
      <id>1</id>
      <name>Amal</name>
      <age B_day ="1995-12-12">22</age>
      <city>Colombo</city>
  </student>

<student gender ="Female">
      <id>2</id>
      <name>Sahani</name>
      <age B_day ="2005-01-10">20</age>
      <city>Mathara</city>
  </student>
  
</students>
